version: '3.8'
services:
  file_app:
    build:
      context: ./file_app
    volumes:
      - ./file_app:/app
      - ./shared:/app/shared
      - ./uploads:/uploads
    #ports:
      #- 50000:50000
      #- 6910-6920:6910-6920
    env_file:
      - .env
    environment:
      - FILE_FOLDER=/uploads
    restart: unless-stopped
  parser:
    build:
      context: ./parsers
    volumes:
      - ./parsers:/app
      - ./shared:/app/shared
    ports:
      - 60000:60000
      #- 6930-6940:6930-6940
    env_file:
      - .env
  db_app:
    build:
      context: ./db_app
    volumes:
      - ./db_app:/app
      - ./shared:/app/shared
    ports:
      - 8000:8000
#      - 6930-6940:6930-6940
    env_file:
      - .env
  db:
    image: "postgres:15.0"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

volumes:
  db_data: